[theme]
primaryColor = "#FF6600"  # Kerry Logistics orange
backgroundColor = "#0A0F16"  # Dark background
secondaryBackgroundColor = "#121920"  # Dark secondary background
textColor = "#E0E7FF"  # Light text for dark mode
base = "dark"  # Force dark theme for all users

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501
pageTitle = "Fleet Intelligence Tracker"
favicon = "🚚" 